CREATE TABLE `coll_instagram_media_window` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`media_id` varchar(50) NOT NULL DEFAULT '',
	`post_id` varchar(50) NOT NULL DEFAULT '',
	`user_id` varchar(50) NOT NULL DEFAULT '',
	`username` varchar(50) NOT NULL DEFAULT '',
	`user_full_name` varchar(100) NOT NULL DEFAULT '',
	`user_profile_picture` varchar(500) NOT NULL DEFAULT '',
	`qraved_user_id` int(11) NOT NULL DEFAULT '0',
	`search_tags` varchar(500) NOT NULL DEFAULT '',
	`post_type` varchar(50) NOT NULL DEFAULT '',
	`media_type` varchar(50) NOT NULL DEFAULT '',
	`carousel_order` int(11) NOT NULL DEFAULT '0',
	`created_date` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
	`tags` text,
	`caption` text,
	`comment_count` int(11) NOT NULL DEFAULT '0',
	`like_count` int(11) NOT NULL DEFAULT '0',
	`link` varchar(500) NOT NULL DEFAULT '',
	`thumbnail_image_width` int(11) NOT NULL DEFAULT '0',
	`thumbnail_image_height` int(11) NOT NULL DEFAULT '0',
	`low_resolution_image_width` int(11) NOT NULL DEFAULT '0',
	`low_resolution_image_height` int(11) NOT NULL DEFAULT '0',
	`standard_resolution_image_width` int(11) NOT NULL DEFAULT '0',
	`standard_resolution_image_height` int(11) NOT NULL DEFAULT '0',
	`low_resolution_video` varchar(500) NOT NULL DEFAULT '',
	`standard_resolution_video` varchar(500) NOT NULL DEFAULT '',
	`low_resolution_video_width` int(11) NOT NULL DEFAULT '0',
	`low_resolution_video_height` int(11) NOT NULL DEFAULT '0',
	`standard_resolution_video_width` int(11) NOT NULL DEFAULT '0',
	`standard_resolution_video_height` int(11) NOT NULL DEFAULT '0',
	`first_fetch_date` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
	`approval_status` varchar(50) DEFAULT 'Pending',
	`approval_user_id` bigint(20) NOT NULL DEFAULT '0',
	`approval_user_name` varchar(200) NOT NULL DEFAULT '',
	`approval_date` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
	`classification` varchar(1000) NOT NULL DEFAULT '',
	`is_deleted` int(4) NOT NULL DEFAULT '0',
	`is_sync_to_rdp` tinyint(1) NOT NULL DEFAULT '0',
	`is_sync_to_celeb` tinyint(1) NOT NULL DEFAULT '0',
	`is_broken_media` tinyint(4) NOT NULL DEFAULT '0',
	`qraved_standard_resolution_image` varchar(500) NOT NULL DEFAULT '',
	`qraved_low_resolution_image` varchar(500) NOT NULL DEFAULT '',
	`qraved_standard_resolution_video` varchar(500) NOT NULL DEFAULT '',
	PRIMARY KEY (`id`),
	KEY `coll_instagram_media_window_media_id` (`media_id`),
	KEY `coll_instagram_media_window_username` (`username`),
	KEY `coll_instagram_media_window_qraved_user_id` (`qraved_user_id`),
	KEY `coll_instagram_media_window_for_qc_list` (`is_deleted`,`media_type`,`approval_status`,`id`),
	KEY `coll_instagram_media_window_approval_status_is_sync_to_rdp` (`approval_status`,`is_sync_to_rdp`),
	KEY `coll_instagram_media_window_post_id_tp_media_tp_appr_st_del` (`post_id`,`post_type`,`media_type`,`approval_status`,`is_deleted`),
	KEY `coll_instagram_media_window_is_broken_media` (`is_broken_media`),
	KEY `coll_instagram_media_window_created_date` (`created_date`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;